services:
  go-noto-elabftw:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: go-noto-elabftw
    container_name: go-noto-elabftw
    restart: always
    volumes:
      - type: bind
        source: ../
        target: /go-noto-elabftw
